//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DemoxOyEntities2 : DbContext
{
    public DemoxOyEntities2()
        : base("name=DemoxOyEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<asiakas> asiakas { get; set; }
    public virtual DbSet<employee> employee { get; set; }
    public virtual DbSet<oppilaat> oppilaat { get; set; }
    public virtual DbSet<testi> testi { get; set; }
    public virtual DbSet<Movies> Movies { get; set; }
}
