//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class asiakas
{
    public string astunnus { get; set; }
    public string asnimi { get; set; }
    public string yhteyshlo { get; set; }
    public string maa { get; set; }
    public string postinro { get; set; }
    public string postitmp { get; set; }
    public Nullable<double> ostot { get; set; }
    public Nullable<short> asvuosi { get; set; }
}

public partial class employee
{
    public int id { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string employeeid { get; set; }
    public string department { get; set; }
}

public partial class Movies
{
    public int id { get; set; }
    public string title { get; set; }
    public string director { get; set; }
    public Nullable<int> year { get; set; }
    public string url { get; set; }
}

public partial class oppilaat
{
    public int id { get; set; }
    public string asioid { get; set; }
    public string etunimi { get; set; }
    public string sukunimi { get; set; }
    public string ryhma { get; set; }
}

public partial class testi
{
    public int id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
}
